openapi: 3.0.0
info:
    title: Notebooks Api
    description: Api for adding notebooks and saving notes, getting questions asked directly into your notebook.
    version: 1.0.0
servers:
    - url: 'http://localhost:8090'
paths:
    /auth/register:
        post:
            summary: Register as a new user
            description: You just need to provide your email and password
            operationId: registerUser
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/register'
                required: true
            responses:
                '200':
                    description: successful registration
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/register'
                '400':
                    description: 'Invalid data'
    /auth/login:
        post:
            summary: Login for existing users
            description: You just need to provide your email and password
            operationId: loginUser
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/login'
                required: true
            responses:
                '200':
                    description: successful login
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/login'
                '400':
                    description: 'Invalid data'

components:
    schemas:
        register:
            type: object
            properties:
                email:
                    type: string
                    format: email
                    example: somename@example.com
                password:
                    type: string
                    format: password
                    example: ';!@$RF#%asd12'
        login:
            type: object
            properties:
                email:
                    type: string
                    format: email
                    example: somename@example.com
                password:
                    type: string
                    format: password
                    example: ';!@$RF#%asd12'
